<?php
if (!defined('ABSPATH')) exit;

class Tranter_Digital_Marketing_Brand_Page {
    public static function init() {
        add_shortcode('te_digital_marketing_brand_page', [__CLASS__, 'page']);
        add_shortcode('te_digital_marketing_brand_development_page', [__CLASS__, 'page']);
        add_shortcode('te_digital_marketing_page', [__CLASS__, 'page']);
    }

    private static function enqueue() {
        wp_enqueue_style('tranter-engine-public-font', 'https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap', [], null);
        wp_enqueue_style('tranter-engine-digital-brand-page', TRANTER_ENGINE_URL . 'assets/css/digital-marketing-brand-page.css', [], TRANTER_ENGINE_VERSION);
    }

    public static function page($atts = []) {
        self::enqueue();
        ob_start();
        echo '<div id="tranter-digital-brand-page">';
        echo self::hero();
        echo self::breadcrumb();
        echo self::what_we_do();
        echo self::capabilities();
        echo self::growth_operations();
        echo self::model();
        echo self::solution_areas();
        echo self::metrics();
        echo self::faq();
        echo self::cta();
        echo self::schema();
        echo '</div>';
        return ob_get_clean();
    }

    private static function hero() { ob_start(); ?>
        <section class="tis-hero" aria-label="AI-enabled Digital Marketing and Brand Development by Tranter IT"><div class="tis-hero-container"><div class="tis-hero-copy"><div class="tis-pill">Digital Marketing & Brand Development</div><h1 class="tis-hero-title">Digital Presence.<span>Built for Growth.</span></h1><p class="tis-hero-text">Build a stronger digital presence with brand strategy, performance campaigns, content systems and AI-assisted insights that help your organisation attract, engage and convert the right audience.</p><div class="tis-hero-actions"><a class="tis-btn tis-btn-primary" href="/wp/contact/" data-tdp-open><span>Book a Demo</span></a><a class="tis-btn tis-btn-outline" href="https://api.whatsapp.com/send/?phone=2348183405221&text=Hello+Tranter+IT%2C+I%20would%20like%20to%20speak%20to%20your%20team%20about%20Digital%20Marketing%20and%20Brand%20Development.&type=phone_number&app_absent=0" target="_blank" rel="noopener"><span>Speak to Our Team</span></a></div></div><div class="tis-hero-panel"><div class="tis-floating-chip">AI marketing layer</div><div class="tis-glass-card"><div class="tis-card-inner"><div class="tis-card-label"><span>Brand Intelligence</span><span class="tis-live"><i></i>Live Performance</span></div><div class="tis-mini-grid"><?php foreach (self::hero_cards() as $card): ?><div class="tis-mini-card"><div class="tis-mini-icon"><?php echo self::icon($card['type']); ?></div><strong><?php echo esc_html($card['title']); ?></strong><span><?php echo esc_html($card['copy']); ?></span></div><?php endforeach; ?></div><div class="tis-strategy-strip"><strong>Marketing systems that improve brand credibility.</strong><span>Not random posts — integrated brand, content and performance systems that help your organisation grow.</span></div></div></div></div></div></section>
    <?php return ob_get_clean(); }

    private static function breadcrumb() { return '<nav class="tis-breadcrumb" aria-label="Breadcrumb"><div class="tis-container"><a href="/wp/">Home</a><span>/</span><a href="/wp/what-we-do/">What We Do</a><span>/</span><strong>Digital Marketing & Brand Development</strong></div></nav>'; }

    private static function what_we_do() { ob_start(); ?>
        <section class="tis-section" id="digital-what-we-do"><div class="tis-container"><?php echo self::header('What We Do', 'Digital Growth Systems for <span>Modern Brands</span>', 'We design brand ecosystems and digital strategies that strengthen organisational positioning while improving customer engagement across digital channels.'); ?><div class="tis-two"><div class="tis-image-card"><img src="https://hipterraafrica.com/wp-content/uploads/2026/02/top-view-hands-typing-keyboard-scaled.jpg" alt="Digital marketing and brand development strategy session" loading="lazy"></div><article class="tis-card tis-copy-card"><h3>Position your organisation for <span>market authority</span></h3><p>We design brand ecosystems and digital strategies that strengthen organisational positioning while improving customer engagement across digital channels.</p><p>Our approach blends strategic messaging, platform design, content development, marketing automation and performance optimisation.</p></article></div></div></section>
    <?php return ob_get_clean(); }

    private static function capabilities() { return self::card_section('digital-brand-capabilities', 'Digital Capabilities', 'Everything Your Brand Needs to <span>Grow with Confidence</span>', 'We support organisations with brand strategy, digital presence, campaign systems and AI-assisted insights that turn visibility into business growth.', [['Brand Strategy & Positioning','Define the message, visual direction, positioning and digital experience that make your brand clearer and more credible.','support'],['Digital Platform Design','Design and optimise websites, landing pages and digital assets that support trust, conversion and commercial performance.','web'],['Content & Messaging Systems','Build content frameworks, storytelling systems and communication assets that help your market understand your value.','security'],['Performance Marketing','Run measurable campaigns across digital channels with performance tracking, optimisation and conversion-focused execution.','growth'],['Marketing Automation','Use automation, segmentation and smart workflows to improve lead nurturing, customer engagement and campaign efficiency.','smart'],['AI-Assisted Brand Intelligence','Use AI-assisted insights to analyse campaigns, content gaps, audience behaviour and opportunities for improvement.','bpo']]); }

    private static function growth_operations() { ob_start(); ?>
        <section class="tis-section" id="digital-growth-operations"><div class="tis-container"><?php echo self::header('AI Brand Intelligence', 'From Trust to <span>Measurable Market Growth</span>', 'Our digital marketing model combines brand strategy, campaign execution, content systems and AI-assisted analytics so your growth becomes easier to plan, measure and scale.'); ?><div class="tis-two"><article class="tis-card tis-copy-card"><h3>Brand development that becomes a <span>growth advantage</span></h3><p>Modern buyers research, compare and decide before speaking to sales. Your brand must communicate credibility, relevance and confidence at every digital touchpoint.</p><p>Tranter helps organisations build digital systems that improve positioning, strengthen demand generation and convert engagement into business opportunities.</p><ul class="tis-list"><li><span class="tis-check">✓</span>Strengthen brand credibility and market positioning</li><li><span class="tis-check">✓</span>Increase audience engagement and brand visibility</li><li><span class="tis-check">✓</span>Improve lead generation and conversion performance</li><li><span class="tis-check">✓</span>Use AI-assisted insights to optimise growth campaigns</li></ul></article><div class="tis-ai-dashboard"><div class="tis-ai-shell"><div class="tis-ai-top"><div class="tis-ai-window"><i></i><i></i><i></i></div><div class="tis-ai-title-small">AI Brand Intelligence Command Centre</div><div class="tis-ai-live">Monitoring Active</div></div><div class="tis-ai-body"><div class="tis-ai-kpis"><div class="tis-ai-kpi"><strong>24/7</strong><span>Campaign coverage</span></div><div class="tis-ai-kpi"><strong>99.8%</strong><span>Brand visibility</span></div><div class="tis-ai-kpi"><strong>AI</strong><span>Market insights</span></div><div class="tis-ai-kpi"><strong>Secure</strong><span>Content control</span></div></div><div class="tis-ai-main"><div class="tis-ai-panel"><div class="tis-ai-head"><strong>Campaign Performance Forecast</strong><span class="tis-ai-chip green">Designed</span></div><div class="tis-ai-bars"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></div><div class="tis-ai-panel"><div class="tis-ai-head"><strong>Growth Readiness</strong><span class="tis-ai-chip">AI Prioritised</span></div><div class="tis-ai-flow"><div class="tis-ai-flow-row"><span>Reach</span><div class="tis-ai-progress"><i style="width:94%"></i></div><span>94%</span></div><div class="tis-ai-flow-row"><span>Leads</span><div class="tis-ai-progress"><i style="width:88%"></i></div><span>88%</span></div><div class="tis-ai-flow-row"><span>Trust</span><div class="tis-ai-progress"><i style="width:91%"></i></div><span>91%</span></div><div class="tis-ai-flow-row"><span>Quality</span><div class="tis-ai-progress"><i style="width:93%"></i></div><span>93%</span></div></div></div></div></div></div></div></div></section>
    <?php return ob_get_clean(); }

    private static function model() { return self::card_section('digital-brand-model', 'Digital Marketing & Brand Development Model', 'A Managed Growth Model for <span>Growing Teams</span>', 'Whether you are building brand visibility, launching campaigns or improving conversion, we help you move from scattered tactics to integrated growth systems.', [['Diagnose','We review your brand position, audience, digital presence, competitors and current performance gaps.','bpo'],['Design','We design brand systems, content architecture, campaign flows and conversion-focused digital experiences.','growth'],['Optimise','We monitor performance, improve campaigns and refine your digital ecosystem for measurable growth.','smart']]); }
    private static function solution_areas() { return self::card_section('digital-solution-areas', 'Our Solutions', 'Digital Marketing Built for <span>Market Growth</span>', 'We create digital solutions that help organisations attract, engage and convert audiences across industries and markets.', [['Brand Strategy & Positioning','Clarify your message, market position and brand experience for stronger trust and recognition.','web'],['Technology & Smart Solution Providers','Explain complex value, scale adoption and increase market leadership through stronger digital positioning.','support'],['Government & Public Sector','Build clearer communication, public trust and campaign visibility for policy, events and service delivery.','bpo'],['Manufacturing & Industrial Companies','Strengthen visibility, product communication and demand generation for industrial markets.','growth'],['Lead Generation & Campaign Systems','Improve demand visibility, service differentiation and lead generation for operational businesses.','security'],['Healthcare & Professional Services','Strengthen credibility, compliance messaging, trust and growth for service-driven organisations.','smart']]); }
    private static function metrics() { $metrics = [['99%','Brand visibility across digital channels'],['24/7','Campaign optimisation and growth support'],['350+','Digital strategy and technology experts'],['AI','AI-assisted campaign intelligence']]; ob_start(); ?><section class="tis-metrics tis-full" aria-label="digital marketing and brand development performance metrics"><div class="tis-container"><div class="tis-metrics-grid"><?php foreach ($metrics as $metric): ?><div class="tis-metric"><strong><?php echo esc_html($metric[0]); ?></strong><span><?php echo esc_html($metric[1]); ?></span></div><?php endforeach; ?></div></div></section><?php return ob_get_clean(); }
    private static function faq() { $faqs = [['What is included in Tranter Digital Marketing & Brand Development?','The service can include brand strategy, messaging, content planning, website and landing page optimisation, campaign execution, digital advertising support, marketing automation and performance reporting.'],['Can you help improve our brand positioning?','Yes. Tranter reviews market, audience, competitors and current communication, then defines clearer positioning, messaging and digital experience standards.'],['How does AI improve digital marketing?','AI can support audience insights, content planning, campaign analysis, lead segmentation, performance optimisation and opportunity discovery.'],['Do you support lead generation campaigns?','Yes. Tranter supports campaign strategy, landing pages, conversion messaging, tracking structures and optimisation for stronger lead generation performance.'],['Can Tranter optimise our website for growth?','Yes. Tranter optimises websites as commercial infrastructure, improving clarity, speed, messaging, conversion paths and alignment with brand and campaign goals.'],['How do we start?','Tranter begins with a discovery conversation to understand brand, target market, digital channels, current performance and growth priorities, then recommends the right roadmap.']]; ob_start(); ?><section class="tis-section tis-faq" id="faq"><div class="tis-container"><?php echo self::header('Frequently Asked Questions', 'Digital Marketing & Brand Development Questions <span>Answered</span>', 'Clear answers for organisations evaluating digital marketing, brand development, campaign optimisation and AI-assisted growth systems.'); ?><div class="tis-faq-grid"><?php foreach ($faqs as $faq): ?><details><summary><?php echo esc_html($faq[0]); ?></summary><div class="answer"><?php echo esc_html($faq[1]); ?></div></details><?php endforeach; ?></div></div></section><?php return ob_get_clean(); }
    private static function cta() { ob_start(); ?><section class="tis-cta tis-full" id="book-a-demo"><div class="tis-container"><h2>Ready to Design <span>Your Growth System?</span></h2><p>Partner with Tranter to build a stronger brand, attract better leads and turn digital visibility into measurable business growth.</p><div class="tis-cta-actions"><a class="tis-btn tis-btn-primary" href="/wp/contact/" data-tdp-open><span>Book a Demo</span></a><a class="tis-btn tis-btn-outline" href="https://api.whatsapp.com/send/?phone=2348183405221&text=Hello+Tranter+IT%2C+I%20would%20like%20to%20speak%20to%20your%20team%20about%20Digital%20Marketing%20and%20Brand%20Development.&type=phone_number&app_absent=0" target="_blank" rel="noopener"><span>Speak to Our Team</span></a></div><div class="tis-trust"><span>Stronger positioning</span><span>Lead generation support</span><span>AI-assisted optimisation</span></div></div></section><?php return ob_get_clean(); }
    private static function card_section($id, $pill, $title, $copy, $items) { ob_start(); ?><section class="tis-section" id="<?php echo esc_attr($id); ?>"><div class="tis-container"><?php echo self::header($pill, $title, $copy); ?><div class="tis-grid-3"><?php foreach ($items as $i => $item): ?><article class="tis-card tis-feature-card"><div class="tis-feature-num"><?php echo esc_html(str_pad($i + 1, 2, '0', STR_PAD_LEFT)); ?></div><div class="tis-feature-icon"><?php echo self::icon($item[2]); ?></div><h3><?php echo esc_html($item[0]); ?></h3><p><?php echo esc_html($item[1]); ?></p></article><?php endforeach; ?></div></div></section><?php return ob_get_clean(); }
    private static function header($pill, $title, $copy) { return '<header class="tis-header"><div class="tis-pill">' . esc_html($pill) . '</div><h2 class="tis-title">' . wp_kses_post($title) . '</h2><div class="tis-divider"><span></span><i></i><span></span></div><p class="tis-subtitle">' . esc_html($copy) . '</p></header>'; }
    private static function hero_cards() { return [['title'=>'Brand Strategy','copy'=>'Clarify your market position, messaging and brand experience across digital touchpoints.','type'=>'support'],['title'=>'Digital Campaigns','copy'=>'Launch performance-focused campaigns designed for visibility, engagement and conversion.','type'=>'security'],['title'=>'AI Insights','copy'=>'Use campaign data, audience signals and content insights to improve decision-making.','type'=>'smart'],['title'=>'Web & Content','copy'=>'Create digital platforms, content assets and experiences that support commercial growth.','type'=>'web']]; }
    private static function schema() { return '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Service","name":"Digital Marketing & Brand Development","serviceType":"Digital Marketing and Brand Development Services","provider":{"@type":"Organization","name":"Tranter IT Infrastructure Services Limited","url":"https://hipterraafrica.com/"},"areaServed":"Global","description":"Digital marketing and brand development services including brand strategy, digital platform design, content systems, performance marketing, marketing automation and AI-assisted campaign intelligence."}</script>'; }
    private static function icon($type) { $icons = ['support'=>'<path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.8-3.8a6 6 0 0 1-8 8l-6.9 6.9a2.1 2.1 0 0 1-3-3l6.9-6.9a6 6 0 0 1 8-8z"/>','security'=>'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="M9 12l2 2 4-4"/>','smart'=>'<path d="M12 2v4M12 18v4M4.9 4.9l2.8 2.8M16.3 16.3l2.8 2.8M2 12h4M18 12h4"/>','web'=>'<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/>','bpo'=>'<path d="M21 16V8a2 2 0 0 0-1-1.7l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.7l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/>','growth'=>'<path d="M4 17l6-6 4 4 6-8"/><path d="M20 7h-5M20 7v5"/>']; $path = $icons[$type] ?? $icons['growth']; return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">' . $path . '</svg>'; }
}
