<?php
if (!defined('ABSPATH')) exit;

class Tranter_HR_Support_Page {
    public static function init() {
        add_shortcode('te_hr_support_page', [__CLASS__, 'page']);
        add_shortcode('te_hr_support_services_page', [__CLASS__, 'page']);
    }

    private static function enqueue() {
        wp_enqueue_style('tranter-engine-public-font', 'https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap', [], null);
        wp_enqueue_style('tranter-engine-hr-support-page', TRANTER_ENGINE_URL . 'assets/css/hr-support-page.css', [], TRANTER_ENGINE_VERSION);
    }

    public static function page($atts = []) {
        self::enqueue();
        ob_start();
        echo '<div id="tranter-hr-support-page">';
        echo self::hero();
        echo self::breadcrumb();
        echo self::what_we_do();
        echo self::capabilities();
        echo self::operations();
        echo self::model();
        echo self::solution_areas();
        echo self::metrics();
        echo self::faq();
        echo self::cta();
        echo self::schema();
        echo '</div>';
        return ob_get_clean();
    }

    private static function hero() { ob_start(); ?>
        <section class="tis-hero" aria-label="Technology-enabled HR Support Services by Tranter IT"><div class="tis-hero-container"><div class="tis-hero-copy"><div class="tis-pill">HR Support Services</div><h1 class="tis-hero-title">Efficient Workforce.<span>Built for Compliance.</span></h1><p class="tis-hero-text">Transform manual people processes into structured HR workflows with workforce visibility and connected systems that help teams operate faster, smarter and more efficiently.</p><div class="tis-hero-actions"><a class="tis-btn tis-btn-primary" href="/wp/contact/" data-te-open-demo><span>Book a Demo</span></a><a class="tis-btn tis-btn-outline" href="https://api.whatsapp.com/send/?phone=2348183405221&text=Hello+Tranter+IT%2C+I%20would%20like%20to%20speak%20to%20your%20team%20about%20HR%20Support%20Services.&type=phone_number&app_absent=0" target="_blank" rel="noopener"><span>Speak to Our Team</span></a></div></div><div class="tis-hero-panel"><div class="tis-floating-chip">HR operations layer</div><div class="tis-glass-card"><div class="tis-card-inner"><div class="tis-card-label"><span>Workforce Intelligence</span><span class="tis-live"><i></i>Live HR Visibility</span></div><div class="tis-mini-grid"><?php foreach (self::hero_cards() as $card): ?><div class="tis-mini-card"><div class="tis-mini-icon"><?php echo self::icon($card['type']); ?></div><strong><?php echo esc_html($card['title']); ?></strong><span><?php echo esc_html($card['copy']); ?></span></div><?php endforeach; ?></div><div class="tis-strategy-strip"><strong>HR support that improves workforce consistency.</strong><span>Not just administration — structured people operations that improve productivity, compliance and team experience.</span></div></div></div></div></div></section>
    <?php return ob_get_clean(); }

    private static function breadcrumb() { return '<nav class="tis-breadcrumb" aria-label="Breadcrumb"><div class="tis-container"><a href="/wp/">Home</a><span>/</span><a href="/wp/what-we-do/">What We Do</a><span>/</span><strong>HR Support Services</strong></div></nav>'; }

    private static function what_we_do() { ob_start(); ?>
        <section class="tis-section" id="hr-what-we-do"><div class="tis-container"><?php echo self::header('What We Do', 'Technology-enabled HR for <span>Modern Teams</span>', 'We support HR teams with systems, processes and operational frameworks that simplify workforce management across multiple locations.'); ?><div class="tis-two"><div class="tis-image-card"><img src="https://tranter-it.com/wp-content/uploads/2026/02/manager-women-working-hiring-application-discussing-curriculum-vitae-with-remote-recruiter-online-videocall-meeting-conference-startup-office-teleconference-call-computer-screen-scaled.jpg" alt="HR support services for workforce operations" loading="lazy"></div><article class="tis-card tis-copy-card"><h3>Motivate and retain talent through <span>innovative HR support</span></h3><p>We support HR teams with systems, processes and operational frameworks that simplify workforce management across multiple locations.</p><p>Our services focus on reducing administrative complexity while improving workforce productivity, employee experience and compliance.</p></article></div></div></section>
    <?php return ob_get_clean(); }

    private static function capabilities() { return self::card_section('hr-support-capabilities', 'HR Capabilities', 'Everything Your Workforce Needs to <span>Operate Better</span>', 'We support HR teams with systems, processes and operational frameworks that simplify workforce administration, improve compliance and strengthen employee experience.', [['HR Operations & Administration','Support employee records, documentation, HR requests, administrative workflows and day-to-day workforce operations.','support'],['Employee Lifecycle Support','Coordinate onboarding, transitions, employee support, HR service requests and lifecycle processes.','web'],['Compliance & Governance','Support HR policies, documentation, process consistency and compliance workflows across teams and locations.','security'],['Workforce Reporting','Create clear visibility into workforce activity, HR operations, service performance and people-process trends.','growth'],['HR Process Optimisation','Reduce administrative complexity through better workflows, structured processes and smarter HR operations.','smart'],['Performance & Productivity Support','Help teams work more efficiently through HR support models that reduce friction and improve workforce productivity.','bpo']]); }

    private static function operations() { ob_start(); ?>
        <section class="tis-section" id="hr-operations"><div class="tis-container"><?php echo self::header('AI Workforce Intelligence', 'From Manual HR Tasks to <span>Structured Workforce Operations</span>', 'Our HR support model combines people operations, workflow structure, compliance discipline and technology enablement so your workforce becomes easier to manage and scale.'); ?><div class="tis-two"><article class="tis-card tis-copy-card"><h3>HR support that becomes a <span>business advantage</span></h3><p>Growing teams need more than basic administration. They need structured HR operations that reduce workload, improve compliance and create consistent employee experiences.</p><p>Tranter helps organisations simplify HR administration, support distributed teams and improve workforce management through practical systems and operating discipline.</p><ul class="tis-list"><li><span class="tis-check">✓</span>Reduce administrative workload for HR teams</li><li><span class="tis-check">✓</span>Improve workforce efficiency and performance visibility</li><li><span class="tis-check">✓</span>Strengthen compliance and governance standards</li><li><span class="tis-check">✓</span>Use reporting and analytics to support better people decisions</li></ul></article><div class="tis-ai-dashboard"><div class="tis-ai-shell"><div class="tis-ai-top"><div class="tis-ai-window"><i></i><i></i><i></i></div><div class="tis-ai-title-small">AI Workforce Intelligence Command Centre</div><div class="tis-ai-live">Monitoring Active</div></div><div class="tis-ai-body"><div class="tis-ai-kpis"><div class="tis-ai-kpi"><strong>24/7</strong><span>HR coverage</span></div><div class="tis-ai-kpi"><strong>99.8%</strong><span>Workforce visibility</span></div><div class="tis-ai-kpi"><strong>AI</strong><span>HR insights</span></div><div class="tis-ai-kpi"><strong>Secure</strong><span>Policy control</span></div></div><div class="tis-ai-main"><div class="tis-ai-panel"><div class="tis-ai-head"><strong>Workforce Operations Forecast</strong><span class="tis-ai-chip green">Structured</span></div><div class="tis-ai-bars"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></div><div class="tis-ai-panel"><div class="tis-ai-head"><strong>Operational Readiness</strong><span class="tis-ai-chip">AI Prioritised</span></div><div class="tis-ai-flow"><div class="tis-ai-flow-row"><span>Admin</span><div class="tis-ai-progress"><i style="width:94%"></i></div><span>94%</span></div><div class="tis-ai-flow-row"><span>Compliance</span><div class="tis-ai-progress"><i style="width:88%"></i></div><span>88%</span></div><div class="tis-ai-flow-row"><span>Visibility</span><div class="tis-ai-progress"><i style="width:91%"></i></div><span>91%</span></div><div class="tis-ai-flow-row"><span>Quality</span><div class="tis-ai-progress"><i style="width:93%"></i></div><span>93%</span></div></div></div></div></div></div></div></div></section>
    <?php return ob_get_clean(); }

    private static function model() { return self::card_section('hr-support-model', 'HR Support Services Model', 'A Managed HR Support Services Model for <span>Growing Teams</span>', 'Whether your workforce is local, distributed or expanding across regions, we help you keep HR operations structured, compliant and consistent.', [['Assess','We review your HR processes, workforce structure, administrative gaps and compliance requirements.','bpo'],['Structure','We design HR support workflows, governance structures and reporting systems that improve consistency.','growth'],['Support','We support ongoing HR operations as your workforce, locations and people-process requirements grow.','smart']]); }
    private static function solution_areas() { return self::card_section('hr-solution-areas', 'Our Solutions', 'HR Support Built for <span>Workforce Growth</span>', 'We support people operations with practical HR services that improve administration, compliance, employee experience and workforce visibility.', [['HR Operations & Administration','Streamline everyday workforce administration, HR requests, documentation, records and operational coordination.','web'],['People & Culture Experience','Improve employee support, workplace communication and people-process consistency across distributed teams.','support'],['Learning & Development','Support workforce capability through structured learning coordination, development tracking and growth programmes.','bpo'],['Rewards & Recognition','Support reward structures, recognition workflows and employee motivation programmes with organised processes.','growth'],['Compliance & HR Governance','Strengthen HR documentation, policy workflows, audit readiness and consistent workforce governance standards.','security'],['HR Reporting & Analytics','Turn HR activity into practical reports and visibility that support planning, decisions and workforce productivity.','smart']]); }
    private static function metrics() { $metrics = [['99%','HR process visibility across distributed teams'],['24/7','HR operations and compliance support'],['350+','Expert HR support and technology teams'],['AI','Workforce reporting and process optimisation']]; ob_start(); ?><section class="tis-metrics tis-full"><div class="tis-container"><div class="tis-metrics-grid"><?php foreach ($metrics as $metric): ?><div class="tis-metric"><strong><?php echo esc_html($metric[0]); ?></strong><span><?php echo esc_html($metric[1]); ?></span></div><?php endforeach; ?></div></div></section><?php return ob_get_clean(); }
    private static function faq() { $faqs = [['What is included in Tranter HR Support Services?','Our HR support services can include HR administration, employee lifecycle support, documentation, workforce reporting, compliance support, HR workflow optimisation and people operations support.'],['Do you support distributed or remote teams?','Yes. Our HR support model is designed for distributed teams, multiple locations and organisations that need consistent HR processes across operating environments.'],['Can Tranter support our existing HR team?','Yes. We can complement your internal HR team by supporting administration, reporting, compliance workflows, employee support and HR process improvement.'],['How does technology improve HR operations?','Technology helps organise employee data, streamline requests, improve reporting, reduce manual workload and create clearer visibility across workforce operations.'],['Is compliance part of your HR support?','Yes. We support HR governance, documentation, policy workflows and operational consistency to help organisations maintain better compliance standards.'],['How do we start?','We begin with a discovery conversation to understand your workforce structure, HR processes, administrative gaps and compliance priorities, then recommend the right support model.']]; ob_start(); ?><section class="tis-section tis-faq" id="faq"><div class="tis-container"><?php echo self::header('Frequently Asked Questions', 'HR Support Services Questions <span>Answered</span>', 'Clear answers for organisations evaluating HR operations support, workforce administration, compliance processes and technology-enabled people services.'); ?><div class="tis-faq-grid"><?php foreach ($faqs as $faq): ?><details><summary><?php echo esc_html($faq[0]); ?></summary><div class="answer"><?php echo esc_html($faq[1]); ?></div></details><?php endforeach; ?></div></div></section><?php return ob_get_clean(); }
    private static function cta() { ob_start(); ?><section class="tis-cta tis-full" id="book-a-demo"><div class="tis-container"><h2>Ready to Structure <span>Your Operations?</span></h2><p>Partner with Tranter to simplify workforce administration, improve compliance and support distributed teams with technology-enabled HR operations.</p><div class="tis-cta-actions"><a class="tis-btn tis-btn-primary" href="/wp/contact/" data-te-open-demo><span>Book a Demo</span></a><a class="tis-btn tis-btn-outline" href="https://api.whatsapp.com/send/?phone=2348183405221&text=Hello+Tranter+IT%2C+I%20would%20like%20to%20speak%20to%20your%20team%20about%20HR%20Support%20Services.&type=phone_number&app_absent=0" target="_blank" rel="noopener"><span>Speak to Our Team</span></a></div><div class="tis-trust"><span>Efficient HR operations</span><span>Compliance support</span><span>Workforce visibility</span></div></div></section><?php return ob_get_clean(); }
    private static function card_section($id, $pill, $title, $copy, $items) { ob_start(); ?><section class="tis-section" id="<?php echo esc_attr($id); ?>"><div class="tis-container"><?php echo self::header($pill, $title, $copy); ?><div class="tis-grid-3"><?php foreach ($items as $i => $item): ?><article class="tis-card tis-feature-card"><div class="tis-feature-num"><?php echo esc_html(str_pad($i + 1, 2, '0', STR_PAD_LEFT)); ?></div><div class="tis-feature-icon"><?php echo self::icon($item[2]); ?></div><h3><?php echo esc_html($item[0]); ?></h3><p><?php echo esc_html($item[1]); ?></p></article><?php endforeach; ?></div></div></section><?php return ob_get_clean(); }
    private static function header($pill, $title, $copy) { return '<header class="tis-header"><div class="tis-pill">' . esc_html($pill) . '</div><h2 class="tis-title">' . wp_kses_post($title) . '</h2><div class="tis-divider"><span></span><i></i><span></span></div><p class="tis-subtitle">' . esc_html($copy) . '</p></header>'; }
    private static function hero_cards() { return [['title'=>'HR Administration','copy'=>'Simplify employee records, requests, documentation and HR support workflows.','type'=>'support'],['title'=>'Compliance Support','copy'=>'Support consistent HR processes, governance and workforce policy alignment.','type'=>'security'],['title'=>'HR Analytics','copy'=>'Improve visibility into workforce activity, trends and operational performance.','type'=>'smart'],['title'=>'Employee Experience','copy'=>'Enable smoother people operations for distributed and hybrid teams.','type'=>'web']]; }
    private static function schema() { return '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Service","name":"HR Support Services","serviceType":"Technology-enabled HR Support Services","provider":{"@type":"Organization","name":"Tranter IT Infrastructure Services Limited","url":"https://hipterraafrica.com/"},"areaServed":"Global","description":"HR support services including workforce administration, employee lifecycle support, compliance workflows, HR reporting, process optimisation and technology-enabled people operations."}</script>'; }
    private static function icon($type) { $icons = ['support'=>'<path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.8-3.8a6 6 0 0 1-8 8l-6.9 6.9a2.1 2.1 0 0 1-3-3l6.9-6.9a6 6 0 0 1 8-8z"/>','security'=>'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="M9 12l2 2 4-4"/>','smart'=>'<path d="M12 2v4M12 18v4M4.9 4.9l2.8 2.8M16.3 16.3l2.8 2.8M2 12h4M18 12h4"/>','web'=>'<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/>','bpo'=>'<path d="M21 16V8a2 2 0 0 0-1-1.7l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.7l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/>','growth'=>'<path d="M4 17l6-6 4 4 6-8"/><path d="M20 7h-5M20 7v5"/>']; $path = $icons[$type] ?? $icons['support']; return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">' . $path . '</svg>'; }
}
